import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Menu from "./menu";
import StoreProvider from "@/redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <Menu />
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
